const locationData = {
    states: ['BIHAR'],
    BIHAR: {
      businessAreas: ['PATNA', 'GAYA', 'BHAGALPUR', 'DARBHANGA', 'MUZAFFARPUR'],
      PATNA: {
        districts: ['PATNA', 'NALANDA', 'BHOJPUR', 'BUXAR'],
        PATNA: ['BIHTA', 'SAMPATCHAL', 'PHULWARI', 'BAKHTIYARPUR', 'DINAPUR', 'MANER', 'PUNPUN', 'KHUSRUPUR', 'FATUHA', 'DHANARUA', 'BELCHCHI', 'PALIGANJ', 'ATHAMALGOLA', 'PANDARAK', 'BARH', 'MOKAMA', 'DULHIN BAZAR', 'MASAURHI', 'BIKRAM', 'NAUBATPUR', 'PATNA SADAR', 'GHOSWARI', 'DANIYAWAN'],
        NALANDA: ['ISLAMPUR', 'BIND', 'KATRISARAI', 'HARNAUT', 'RAJGIR', 'RAHUI', 'NOORSARAI', 'NAGAR NAUSA', 'BIHARSHARIF', 'SILAO', 'HILSA', 'EKANGARSARI', 'GIRIAK', 'KARAI PARUSURAI', 'THARTHARI', 'CHANDI', 'PARBALPUR', 'SARMERA', 'BEN', 'ASTHAWAN'],
        BHOJPUR: ['AGIAON', 'SHAHPUR', 'SANDESH', 'BARHARA', 'SAHAR', 'ARA', 'KOLIWAR', 'BEHEA', 'TARARI', 'PIRO', 'CHARPOKHARI', 'UDWANTNAGAR', 'GARHANI', 'JAGDISHPUR'],
        BUXAR: ['NAWANAGAR', 'BRAHMPUR', 'DUMRAON', 'CHAUSA', 'CHOUGAIN', 'ITARHI', 'RAJPUR', 'BUXAR', 'SIMRI', 'KESATH', 'CHAKKI']
      },
      GAYA: {
        districts: ['ROHTAS', 'NAWADA', 'ARWAL', 'GAYA', 'JEHANABAD', 'AURANGABAD', 'KAIMUR(BHABUA)'],
        ROHTAS: ['SURAJPURA', 'SANJHOULI', 'DINARA', 'CHENARI', 'NAWHATTA', 'DEHRI', 'BIKRAMGANJ', 'ROHTAS', 'KOCHAS', 'NOKHA', 'TILOUTHU', 'NASRIGANJ', 'RAJUPUR', 'SASARAM', 'KARAKAT', 'KARGAHAR', 'DAWATH', 'AKHORIGOLA', 'SHEOSAGAR'],
        NAWADA: ['MESCAUR', 'NARHAT', 'NARDIGANJ', 'AKBARPUR', 'GOBINDPUR', 'ROH', 'KASHICHAK', 'RAJAULI', 'PAKRI BARAWAN', 'NAWADA', 'WARISALIGANJ', 'SIRDALA', 'KAWAKOLE', 'HISUA'],
        ARWAL: ['ARWAL', 'KALER', 'KAPRI', 'KURTHA', 'SONBHADRA-BANSI-SURAJPUR'],
        GAYA: ['DUMARIA', 'KHIZARSARAI', 'MOHRA', 'GURARU', 'IMAMGANJ', 'BARACHATTI', 'BODHGAYA', 'ATRI', 'AMAS', 'PARAIYA', 'WAZIRGANJ', 'SHERGHATTY', 'FATEHPUR', 'MOHANPUR', 'NEEMCHAK BATHANI', 'MANPUR', 'KONCH', 'BELAGANJ', 'GAYA TOWN', 'TEKARI', 'BANKEY BAZAR', 'TANKUPPA', 'DOBHI'],
        JEHANABAD: ['KAKO', 'JEHANABAD', 'RATNI FARIDPUR', 'GHOSHI', 'HULASGNAJ', 'MODANGANJ', 'MAKHUMPUR'],
        AURANGABAD: ['HASPURA', 'KUTUMBA', 'GOH', 'BARUN', 'RAFIGANJ', 'NABINAGAR', 'DEO', 'DAUDNAGAR', 'MADANPUR', 'AURANGABAD', 'OBRA'],
        'KAIMUR(BHABUA)': ['RAMGARH', 'ADHAURA', 'KUDRA', 'BHABUA', 'RAMPUR', 'DURGAWATI', 'MOHANIA', 'BHAGWANPUR', 'CHAND', 'CHAINPUR', 'NUAON']
      },
      BHAGALPUR: {
        districts: ['SHEIKHPURA', 'MUNGER', 'BANKA', 'LAKSHISARAI', 'BHAGALPUR', 'ARARIA', 'PURNIA', 'JAMUI', 'KATIHAR', 'KISHANGANJ'],
        SHEIKHPURA: ['ARIARI', 'BARBIGHA', 'CHEWARA', 'GHAT KUSUMBHA', 'SHEIKHOPUR SARAI', 'SHEIKHPURA'],
        MUNGER: ['DHARHARA', 'JAMALPUR', 'SANGRAMPUR', 'TETIABAMBAR', 'MUNGER SADAR', 'BARIYARPUR', 'TARAPUR', 'ASARGANJ', 'KHARAGPUR'],
        BANKA: ['CHANNAN', 'KATORIA', 'AMARPUR', 'BELHAR', 'DHURAIYA', 'BAUSI', 'BANKA', 'BARAHAT', 'FULLIDUMAR', 'RAJAUN', 'SHAMBHUGANJ'],
        LAKSHISARAI: ['BARAHIYA', 'CHANNAN', 'HALSI', 'LAKHISARAI', 'PIPARIYA', 'RAMGARH CHOWK', 'SURAJGARHA'],
        BHAGALPUR: ['NARAYANPUR', 'GORADIH', 'PIRPAINTI', 'NAUGACHHIA', 'KHARIK', 'SABOUR', 'KAHALGAON', 'RANGRACHOWK', 'ISMAILPUR', 'GOPALPUR', 'SULTANGANJ', 'NATHNAGAR', 'SONHAULA', 'JAGDISHPUR', 'BIHPUR', 'SHAHKUND'],
        ARARIA: ['RANIGANJ', 'FORBESGANJ', 'KURSAKAΝΤΑ', 'PALASI', 'NARPATGANJ', 'BHARGAMA', 'JOKIHAT', 'SIKTY', 'ARARIA'],
        PURNIA: ['RUPOULI', 'SRINAGAR', 'AMOUR', 'BAISA', 'BANMANKHI', 'PURNIA EAST', 'BARHARA', 'DAGRAUA', 'BAISI', 'KRITYANAND NAGAR', 'DHAMDAHA', 'JALALGARH', 'KASBA', 'BHAWANIPUR'],
        JAMUI: ['BARHAT', 'SIKANDRA', 'ISLAMNAGAR ALIGANJ', 'JAMUI', 'JHAJHA', 'SONO', 'KHAIRA', 'LAXMIPUR', 'GIDHOR', 'CHAKAI'],
        KATIHAR: ['MANIHARI', 'DANDKHORA', 'KADWA', 'BALRAMPUR', 'KORHA', 'FALKA', 'SAMELI', 'HASANGANJ', 'KURSELA', 'MANSAHI', 'KATIHAR', 'AZAMNAGAR', 'BARARI', 'PRANPUR', 'BARSOI', 'AMDABAD'],
        KISHANGANJ: ['POTHIA', 'BAHADURGANJ', 'THAKURGANJ', 'DIGHALBANK', 'KOCHADHAMAN', 'TERHAGACHH', 'KISHANGANJ']
      },
      DARBHANGA: {
        districts: ['BEGUSARAI', 'SAHARSA', 'DARBHANGA', 'MADHEPURA', 'SAMASTIPUR', 'MADHUBANI', 'SUPAUL', 'KHAGARIA'],
        BEGUSARAI: ['GADHUPURA', 'SAHEBPUR KAMAL', 'BARAUNI', 'DANDARI', 'CHERIA BARIARPUR', 'BEGUSARAI', 'NAWKOTHI', 'KHODAWANDPUR', 'BALLIA', 'BAKHRI', 'TEGHRA', 'BIRPUR', 'BHAGWANPUR', 'SAMHO AKHA KURHA', 'MANSURCHAK', 'CHHAURAHI', 'BACHHWARA', 'MATIHANI'],
        SAHARSA: ['SOUR BAZAR', 'KAHARA', 'NAUHATTA', 'SONBARSA', 'BANMA ITAHARI', 'SATTAR KATTAIYA', 'SALKHUA', 'PATARGHAT', 'MAHISHI', 'SIMRI BAKHTIARPUR'],
        DARBHANGA: ['GHANSHYAMPUR', 'KUSHESWAR ASTHAN EAST', 'KUSHESHWAR ASTHAN', 'DARBHANGA', 'JALE', 'HAYAGHAT', 'BIRAUL', 'SINGHWARA', 'TARDIH', 'MANIGACHHI', 'HANUMAN NAGAR', 'BENIPUR', 'BAHERI', 'GAURABAURAM', 'KEOTIRUNWAY', 'ALINAGAR', 'BAHADURPUR', 'KIRATPUR'],
        MADHEPURA: ['UDA KISHANGANJ', 'PURANI', 'GHELARH', 'GAMHARIYA', 'SHANKARPUR', 'CHAUSA', 'ALAMNAGAR', 'SINGHESHWAR', 'GWALPARA', 'MADHEPURA', 'KUMARKHAND', 'BIHARIGANJ', 'MURLIGANJ'],
        SAMASTIPUR: ['WARISNAGAR', 'BITHAN', 'SARAIRANJAN', 'DALSINGHSARA', 'KHANPUR', 'MOHIUDDINAGAR', 'VIDYAPATI NAGAR', 'PATORI', 'MORWA', 'KALYANPUR', 'ROSERA', 'HASANPUR', 'TAJPUR', 'SAMASTIPUR', 'MOHANPUR', 'BIBHUTPUR', 'PUSA', 'SHIVAJI NAGAR', 'SINGHIA', 'UJIARPUR'],
        MADHUBANI: ['PHULPARAS', 'LAUKAHA (KHUTAUNA)', 'RAJNAGAR', 'LADANIA', 'PANDAUL', 'KALUAHI', 'NIRMALI', 'MADHWAPUR', 'MADHEPUR', 'JHANJHARPUR', 'BABU BARHI', 'GHOGHARDIHA', 'BENIPATTI', 'KHAJAULI', 'BISFI', 'LAKHNAUR', 'RAHIKA', 'MADHUBANI', 'BASOPATTI', 'MARAUNA', 'ANDHRATHARHI', 'LAUKAHI', 'HARLAKHI', 'JAINAGAR'],
        SUPAUL: ['BASANTPUR', 'TRIBENIGANJ', 'KISHANPUR', 'NIRMALI', 'PRATAPGANJ', 'SUPAUL', 'SARAIGARH BHARTIYAHI', 'RAGHOPUR', 'CHHATAPUR', 'PIPRA'],
        KHAGARIA: ['MANSI', 'GOGRI', 'KHAGARIA', 'BELDAUR', 'CHAUTHAM', 'PARBATTA', 'ALAULI']
      },
      MUZAFFARPUR: {
        districts: ['SIWAN', 'SITAMARHI', 'VAISHALI', 'PASHCHIM CHAMPARAN', 'SHEOHAR', 'GOPALGANJ', 'PURBI CHAMPARAN', 'MUZAFFARPUR', 'SARAN'],
        SIWAN: ['SIWAN', 'GUTHANI', 'MAIRWA', 'BHAGWANPUR HAT', 'DARAULI', 'SISWAN', 'DARAUNDHA', 'RAGHUNATHPUR', 'HUSSAINGANJ', 'BARHARIA', 'ANDAR', 'BASANTPUR', 'MAHARAJGANJ', 'NAUTAN', 'ZIRADEI', 'PACHRUKHI', 'HASAN PURA', 'GORIAKOTHI', 'LAKRI NABIGANJ'],
        SITAMARHI: ['PARSAUNI', 'RUNNISAIDPUR', 'BATHANAHA', 'PUPRI', 'SUPPI', 'SURSAND', 'SONBARSA', 'BAJPATTI', 'MAJORGANJ', 'CHORAUT', 'BOKHRA', 'NANPUR', 'PARIHAR', 'RIGA', 'BELSAND', 'BAIRGANIA', 'DUMRA'],
        VAISHALI: ['SAHDEI BUZURG', 'MAHNAR', 'HAJIPUR', 'BIDUPUR', 'VAISHALI', 'MAHUA', 'PATEDHI BELSAR', 'RAJAPAKAR', 'CHEHRAKALA', 'JANDAHA', 'RAGHOPUR', 'PATEPUR', 'GARAUL', 'BHAGWANPUR', 'DESRI', 'LALGANJ'],
        'PASHCHIM CHAMPARAN': ['SIKTA', 'THAKRAHAN', 'MAJHAULIA', 'PIPRASI', 'BETTIAH', 'MAINATAND', 'LAURIYA', 'BAGAHA-II', 'NARKATIAGANJ', 'NAUTAN', 'RAMNAGAR', 'BAGAHA-I', 'CHANPATIA', 'GAUNAHA', 'BAIRIA', 'MADHUBANI', 'JOGAPATTI'],
        SHEOHAR: ['DUMARI KATSARI', 'PIPRAHI', 'PURNAHIYA', 'SHEOHAR', 'TARIYANI'],
        GOPALGANJ: ['BHOREY', 'GOPALGANJ', 'KATAIYA', 'UCHKAGAON', 'MANJHA', 'SIDHWALIYA', 'PHULWARIYA', 'PANCHDEORI', 'KUCHAIKOTE', 'BARAULI', 'BAIKUNTHPUR', 'HATHUA', 'THAWE', 'BIJAIPUR'],
        'PURBI CHAMPARAN': ['CHAWRADANO', 'BANJARIYA', 'TETARIYA', 'GHORASAHAN', 'MEHSI', 'RAXAUL', 'RAMGARHWA', 'CHIRAIYA', 'KESARIA', 'ADAPUR', 'KOTWA', 'SUGAULI', 'TURKAULIA', 'KALYANPUR', 'PATAHI', 'SANGRAMPUR', 'DHAKA', 'HARSIDHI', 'PAKRIDAYAL', 'MADHUBAN', 'ARERAJ', 'BANKATWA', 'CHAKIA (PIPRA)', 'MOTIHARI', 'PAHARPUR', 'PIPRA KOTHI', 'PHENHARA'],
        MUZAFFARPUR: ['MURAUL', 'SARAIYA', 'GAIGHAT', 'BOCHAHAN', 'MOTIPUR', 'KURHANI', 'SAHEBGANJ', 'BANDRA', 'MARWAN', 'PAROO', 'KANTI', 'KATRA', 'AURAI', 'MINAPUR', 'SAKRA', 'MUSHAHARI'],
        SARAN: ['TARAIYA', 'ISUAPUR', 'MARHAURAH', 'BANIAPUR', 'NAGRA', 'DIGHWARA', 'MAKER', 'SONEPUR', 'CHHAPRA', 'GARKHA', 'MASHRAKΗ', 'PARSA', 'JALALPUR', 'EKMA', 'MANJHI', 'AMNOUR', 'DARIAPUR', 'LAHLADPUR', 'PANAPUR', 'REVELGANJ']
      }
    }
  };


  export default locationData;