# Generated by Django 5.2 on 2025-05-07 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtasks', models.TextField(blank=True)),
                ('milestone', models.CharField(choices=[('desktop_survey_design', 'Desktop Survey Design'), ('network_health_checkup', 'Network Health Checkup'), ('hoto_existing', 'HOTO-Existing'), ('detailed_design', 'Detailed Design'), ('row', 'ROW (Right of Way)'), ('ifc', 'IFC (Issued for Construction)'), ('ic', 'IC (Initial Construction)'), ('as_built', 'As-Built'), ('hoto_final', 'HOTO (Final)'), ('field_survey', 'Field Survey')], max_length=50)),
                ('status', models.CharField(choices=[('nil', 'Nil'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('business_area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
    ]
